feat(scripts): support OpenRC init system
lkrg-org/lkrg pull request #197
Opened 2022-07-03 22:28 UTC by mrl5

### Description
introduce OpenRC bootup scripts

### How Has This Been Tested?
I've tested it by running
```console
# make install uninstall
```
on OpenRC system ([funtoo linux](https://www.funtoo.org))

2022-07-04 10:26 UTC, solardiz commented on README
> +------------
You'll need to rename and revise the "Uninstalling and upgrading" section then - it should probably become just "Upgrading" and should refer to the section "Uninstalling" instead of partially repeating its content.

2022-07-04 10:32 UTC, solardiz commented on README
> +for systemd:
Style: you don't follow these with colons in your additions to other sections, so either should not do so here or should revise all of them. I'd do the latter, e.g.:

```
You can also use the following command to temporarily stop the LKRG service
without uninstalling it, for systemd:
```

and then it's natural to have the rest just like you wrote them here in `Uninstalling`.

2022-07-04 10:34 UTC, solardiz commented on README
> +system).
Should be "a supported init system" (add "a ") in both places. Also, two spaces before "Meanwhile" for consistent style with the rest of the file.

2022-07-04 10:38 UTC, solardiz commented on README
> +following command:
Please replace this sentence with:

```
In order to automatically load LKRG into the Linux kernel on each bootup run
the following command:
```

2022-07-04 10:42 UTC, solardiz commented on scripts/bootup/openrc/lkrg
> +# Distributed under the terms of the GNU General Public License v2
Why did you feel it important to specify license in this one tiny file and not in others? We do have top-level `LICENSE` specify GPLv2, so this feels unneeded (would have made sense if you specified a more relaxed license here).

2022-07-04 16:01 UTC, mrl5 commented on README
> +the LKRG module if kernel was booted with this paramter.
yup, I've checked and confirm that `p_lkrg` doesn't want to load with this option :)

2022-07-04 17:43 UTC, solardiz commented
@mrl5 Also, you seem to have a GitHub-provided noreply e-mail address on the commit. You might want to change that to an address of your own, which you'd then add to your GitHub account.

2022-07-04 17:47 UTC, solardiz commented
@mrl5 Is there any way for me to contact you about the misunderstandings I see in comments at https://bugs.funtoo.org/browse/FL-10115? That would be off-topic to discuss on this pull request.

2022-07-04 18:17 UTC, mrl5 commented
> @mrl5 Is there any way for me to contact you about the misunderstandings I see in comments at https://bugs.funtoo.org/browse/FL-10115? That would be off-topic to discuss on this pull request.

I've sent PM to your twitter account: https://twitter.com/solardiz

2022-07-04 18:44 UTC, mrl5 commented on README
> +following command:
> Please replace this sentence with:
> 
> ```
> In order to automatically load LKRG into the Linux kernel on each bootup run
> the following command:
> ```

ok will do. for the record I've taken `add` from `man modprobe` :D
>       modprobe - Add and remove modules from the Linux Kernel

2022-07-04 18:48 UTC, mrl5 commented on scripts/bootup/openrc/lkrg
> +# Distributed under the terms of the GNU General Public License v2
that's a good question - actually I did it per analogy to most of the scripts that are in `/etc/init.d/*` on my OS:
```console
$ head -n 3 /etc/init.d/* | grep -i license | wc -l
61
$ ls -l /etc/init.d | wc -l
106
```
but I can remove this line if you really want to

2022-07-04 19:55 UTC, solardiz requested changes
Looks almost ready.

2022-07-04 19:55 UTC, solardiz commented on CHANGES
> +The following major changes have been made between LKRG 0.9.3 and 0.9.4:
We generally only include the next version number in `CHANGES` shortly before making the release, and until then use something like "since LKRG 0.9.3".

2022-07-04 19:55 UTC, solardiz commented on README
> +- OpenRC
I'd shorten this to one line:

```
Currently there are dedicated scripts for systemd and OpenRC.
```

2022-07-04 19:55 UTC, solardiz commented on README
> +OS without a supported init system you can let "sudo make install" partially
Should be "an" before "OS", or use "distribution" in place of "OS". (I understand you don't want to write "system" referring to two different things in the same sentence.)

2022-07-04 19:55 UTC, solardiz commented on README
> +- for systemd:
I'm fine with this style, but I'd save two lines by writing:

```
Run the following command to start the LKRG service, for systemd:
```

and then omit the leading "- " before "for OpenRC" and "for other".

Ditto in other places, so making the text significantly shorter.

2022-07-04 19:55 UTC, solardiz commented on README
>  the source code tree of the new version may or may not work correctly).
I think this paragraph about the directory should stay in "Uninstalling", not be in "Upgrading", which should refer to "Uninstalling" for it.

2022-07-04 19:55 UTC, solardiz commented on README
> +this paramter.
Add "the" before "kernel", fix typo in "paramter".

2022-07-04 19:55 UTC, solardiz commented on scripts/bootup/openrc/lkrg
> +# Distributed under the terms of the GNU General Public License v2
OK, up to you.

2022-07-05 13:25 UTC, solardiz commented
@mrl5 BTW, for the sysctl file to provide (almost-)initial LKRG configuration, LKRG needs to be loaded _before_ that file is processed. However, I don't see anything in the init script that would indicate its priority vs. other scripts. Did you look into that?

It's also desirable for security that LKRG be loaded before services such as sshd, cron, MTA/MDA, and unloaded late on system shutdown (if at all).

On pre-systemd Red Hat'ish systems with `chkconfig`, this would be controlled with lines like `# chkconfig: 2345 55 25` in init files (comments for the shell, but magic for `chkconfig`). These indicated runlevels (`2345` here) and start and stop priorities vs. other init scripts (`55` and `25` here). Does OpenRC have anything similar? Does Funtoo use that?

Quite possibly we'll eventually drop unloading of LKRG on system shutdown somehow. This is currently mostly a side-effect of our uninstall/upgrade instructions.

2022-07-05 21:35 UTC, mrl5 commented
> @mrl5 BTW, for the sysctl file to provide (almost-)initial LKRG configuration, LKRG needs to be loaded _before_ that file is processed (edit: otherwise those settings would not take effect at all). However, I don't see anything in the init script that would indicate its priority vs. other scripts. Did you look into that?
> 
> It's also desirable for security that LKRG be loaded before services such as sshd, cron, MTA/MDA, and unloaded late on system shutdown (if at all).
> 
> On pre-systemd Red Hat'ish systems with `chkconfig`, this would be controlled with lines like `# chkconfig: 2345 55 25` in init files (comments for the shell, but magic for `chkconfig`). These indicated runlevels (`2345` here) and start and stop priorities vs. other init scripts (`55` and `25` here). Does OpenRC have anything similar? Does Funtoo use that?
> 
> Quite possibly we'll eventually drop unloading of LKRG on system shutdown somehow. This is currently mostly a side-effect of our uninstall/upgrade instructions.

thanks for bringing this up. it actually made me to take a step back and ask this question: https://github.com/lkrg-org/lkrg/issues/109#issuecomment-1175514381

TBH the only reason why I decided to do this pull request was to make OpenRC service per analogy to the existing systemd one. But now I'm really thinking to give up this idea and simply fall back to [modules-load.d](https://www.freedesktop.org/software/systemd/man/modules-load.d.html).

I'm pretty sure OpenRC takes care of correct loading order when [modules-load.d](https://www.freedesktop.org/software/systemd/man/modules-load.d.html) is detected (like mentioned first sysctl file then modules as well as modules before other services). Additionally I don't think that it would unload the modules before shutdown.

If you agree with above statement I'd be happy to modify `README` to include some instructions for [modules-load.d](https://www.freedesktop.org/software/systemd/man/modules-load.d.html)

2022-07-05 22:22 UTC, solardiz commented
> I'm pretty sure OpenRC takes care of correct loading order when [modules-load.d](https://www.freedesktop.org/software/systemd/man/modules-load.d.html) is detected

What makes you so sure?

> like mentioned first sysctl file then modules

For LKRG, it should be the other way around! The sysctl's can't be applied before the module is loaded, they simply don't exist yet. For some other module, it could be different - maybe that other module does not have its own sysctl's, but its loading is affected by the kernel's sysctl settings. So there isn't a universal "correct" order that an init system could use.

Anyway, longer term we should probably move away from usage of sysctl's for initial configuration. We intended module parameters to be used for that, but then got contributed this file with all sysctl's based on our `README`, and I understand it's more convenient to edit than a list of module parameters all on one line, but it's also less reliable and is inherently racy.

> I'd be happy to modify README to include some instructions for [modules-load.d](https://www.freedesktop.org/software/systemd/man/modules-load.d.html)

Then we also need instructions for passing parameters to modules loaded that way.

Since you started this PR with an almost ready contribution, I thought we could accept it for now, then _possibly_ drop both systemd and OpenRC specifics at some later time.

2022-07-05 22:26 UTC, mrl5 commented
> What makes you so sure?
It's an assumption :D sorry - it might sound misleading

> Since you started this PR with an almost ready contribution, I thought we could accept it for now, then possibly drop both systemd and OpenRC specifics at some later time.
very well then - let me go through 2nd iteration of your CR so that I can apply fixes. I'll click on `re-request review` once I think I'm ready

2022-07-05 23:07 UTC, mrl5 commented
@solardiz for my convenience I decided to gather requirements for proper way of handling `p_lkrg` module by the init system dedicated service (I'm using [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119) nomenclature):
1. it MUST load `p_lkrg` module before sysctl config files are processed (esp. `/etc/sysctl.d/01-lkrg.conf`)
2. it MUST load `p_lkrg` module as early after bootup as possible (esp. before services such as sshd, cron, MTA/MDA are started)
3. it MUST unload `p_lkrg` module on explicit user command
4. it SHOULD NOT unload `p_lkrg` module automatically at shutdown
5. it MAY not load `p_lkrg` module if `nolkrg` kernel parameter was provided

pls suggest changes to above if I missed sth or misunderstood sth.

2022-07-06 10:20 UTC, solardiz commented
@mrl5 You got those requirements (1, 2, 3) and preferences (4, 5) right. The changes you suggest in "update" are also within consideration. Thanks!

2022-07-08 09:00 UTC, solardiz commented on scripts/bootup/openrc/lkrg
> +}
I'm OK with this approach, although I thought you could probably check `runlevel` from within `stop`. Is there a working `runlevel` command on systems with OpenRC?

2022-07-08 17:50 UTC, mrl5 commented on scripts/bootup/openrc/lkrg-openrc.sh
> +	/etc/init.d/lkrg stop
I've managed to move everything to `stop` command keeping [the requirements](https://github.com/lkrg-org/lkrg/pull/197#issuecomment-1175588110)

thanks for the `runlevel` hint in this comment https://github.com/lkrg-org/lkrg/pull/197#discussion_r916613571

2022-07-08 20:39 UTC, solardiz approved these changes
This looks ready to me. I just raised one minor concern - please feel free to make an adjustment (and re-test) or let me know that you're leaving things as they are (and I'll merge as-is). Thanks!

2022-07-08 20:39 UTC, solardiz commented on scripts/bootup/openrc/lkrg
> +	if [[ $($runlevel_command) =~ (S|0|1|6)$ ]]; then
Maybe add a space before each runlevel value we check, so that we'd only match on the second token in `runlevel` output? At least for me, `runlevel` outputs two tokens - previous and current runlevels. Here, the previous can potentially be single-user mode, from which the sysadmin might have exited into multi-user. We probably do want to load LKRG in that case.

I mean:

```bash
	if [[ $($runlevel_command) =~ ( S| 0| 1| 6)$ ]]; then
```

Of course, you need to re-test it.

BTW, is it safe to assume the shell is `bash` here?

2022-07-08 20:43 UTC, solardiz commented
BTW, note that this PR looks like it'll clash with #200. I hope you don't mind rebasing if we happen to merge that other one first.

2022-07-08 20:45 UTC, mrl5 commented
> BTW, note that this PR looks like it'll clash with #200. I hope you don't mind rebasing if we happen to merge that other one first.

I don't mind rebasing in case of git conflict :) I hope you don't mind reviewing one more time in case this happens :D

2022-07-08 22:35 UTC, mrl5 commented on scripts/bootup/openrc/lkrg
> +	if [[ $($runlevel_command) =~ (S|0|1|6)$ ]]; then
> Maybe add a space before each runlevel value we check, so that we'd only match on the second token in `runlevel` output? At least for me, `runlevel` outputs two tokens - previous and current runlevels. Here, the previous can potentially be single-user mode, from which the sysadmin might have exited into multi-user. We probably do want to load LKRG in that case.

why not - I'll do it. For the record though, my understanding of `$` regex anchor, `man 8 init` and `man 8 runlevel` is that there shouldn't be any bug with current regex

> BTW, is it safe to assume the shell is bash here?

good point - better safe than sorry - actually I'm not sure how `#!/sbin/openrc-run` works under the hood

2022-07-08 23:05 UTC, solardiz commented
Looks good to me. I'll merge now. Thank you!

2022-07-08 23:05 UTC, merged