Unified log messages
lkrg-org/lkrg pull request #202
Opened 2022-07-14 04:09 UTC by solardiz

### Description

These are significant changes throughout the tree. The aim is to make log (and kernel panic) messages more consistent and suitable for both automated analysis and human consumption, but several other subtly related changes are also made. With all of these, our source code is shortened by 1700+ lines:

```
 72 files changed, 1144 insertions(+), 2887 deletions(-)
```

The changes are split across 23 commits. However, many of them are in one of those commits, which felt illogical to split in parts:

```
 60 files changed, 581 insertions(+), 1848 deletions(-)
```

- The first few commits fix minor bugs/issues I happened to notice while working on this
- Then logging macros are revised, in particular introducing LKRG's own message severities and categories, which are separate from (but mapped onto) the kernel's and are included in messages themselves (so no information is lost in the many-to-one mapping)
- Many of the messages are now constructed by context-specific macros, which greatly reduced the number of "message templates" to maintain manually
- Some other functionality near the logging (such as kernel symbol lookups, integrity checks, and integrity violation counting) has also been moved into the macros or functions, so it became more consistent too
- Some duplication in checks and logging between caller and callee functions has been removed, so in some scenarios fewer messages should now be produced
- The actual messages and their severities/categories are revised (in particular, security alerts are now separated from other faults, whereas previously the same highest severity was also used for faults)
- For alerts, there's are sub-fields indicating detection vs. response and affected component category (e.g., task vs. kernel vs. CPU)
- All debugging messages use low severities now (previously, some used even the highest severity assuming that debugging wouldn't normally be enabled)

### How Has This Been Tested?

Our CI was happy. Curiously, once I added detection of `ALERT`/`FAULT`/`FATAL` messages to CI, one of its 18 tests (the `mkosi-mainline` one) failed on `IOMMU table can't be found (skipping)`. So I had to downgrade this message from `FAULT` (like I had it at that time) to `ISSUE` (or we could exclude lack of `FAULT` messages from CI requirements).

I also tested builds with `make DEBUG=on` (enables `P_LKRG_DEBUG_BUILD`), and on the contrary with `#define P_LKRG_DEBUG` (default on) commented out. (There's still the weirdness of `P_LKRG_DEBUG` vs. `P_LKRG_DEBUG_BUILD` not addressed here.)

I also tested different settings of `log_level`.

Finally, I tested detection of and response to https://github.com/chompie1337/Linux_LPE_eBPF_CVE-2021-3490 on a vulnerable Ubuntu kernel.

More testing is very welcome. In particular, with code hacks (such as inverting `if` conditions) to trigger many/all of the messages and see that they look correct (for those conditions). Also, testing to make sure we respond to detected attacks no worse than before. In some cases, _duplicate_ logging and response should now disappear, but non-duplicate must stay!

Code review is also welcome. Adam took a look at my work-in-progress already, but that isn't a thorough review, and more eyes can catch more bugs.

@oshogbo Maybe you want to help with review and testing? Some of these changes are similar in spirit to the kind of cleanups you contributed before (and that we'll need more of). Thanks!

2022-07-15 16:21 UTC, Adam-pi3 commented
@solardiz when we do print the pointers, it is for debugging purpose and better understand the state (or the problem) which put LKRG in that specific piece of code. Linux kernel trying to prevent the pointer leaks in a "default" configuration by modifying behavior of `%p` and keep adding new formaters  which allows to print a real value of the pointer. Our approach of using `0x%lx` is reliable across all the kernel and configurations. We do not print it during the default logging configuration so we should be fine.

2022-07-15 19:58 UTC, Adam-pi3 requested changes

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_ERR, "kmem_cache_create() for exploit detection pCFI error! :(\n");
Shouldn't we have the info about the problem here?

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_CRIT,
Why removing it?

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +#define P_PRINT_LOG_STACK(what) \
Move to `.h`

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +   if (unlikely(p_sp & (sizeof(long) - 1))) {
I guess we should just remove it

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +   P_SYM_INIT(selinux_enabled, int *)
Now, I'm thinking maybe we should continue in case of this error and just not enforce SELinux validation?

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.h
> -int p_print_task_f(void *p_arg);
We should keep it but e.g., wrap in some DEBUG build

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_rb_ed_trees/p_rb_ed_pids/p_rb_ed_pids_tree.c
> -      p_print_log(P_LKRG_ERR, "kmem_cache_create() for ED PIDs error! :(\n");
Shouldn't we print it?

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/__x32/p_x32_sys_keyctl/p_x32_sys_keyctl.c
> -         p_print_log(P_LKRG_INFO, "Updating ED pid[%d]\n",current->pid);
Why remove it?

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/caps/p_cap_task_prctl/p_cap_task_prctl.c
> -         p_print_log(P_LKRG_INFO, "Updating ED pid[%d]\n",current->pid);
Same here

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/caps/p_sys_capset/p_sys_capset.c
> -         p_print_log(P_LKRG_INFO, "Updating ED pid[%d]\n",current->pid);
In fact, everywhere where we update pid i think we should keep the info (also the one below as well)

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/pCFI/p_mark_inode_dirty/p_mark_inode_dirty.c
> -#if 0
This code can generate a human readable path not just inode - i wonder if we should delete it or keep in some debug option. Although I didn't test it on newer kernels

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/p_install.c
> + * does not expose the p_fatal flag in here.  It does a final P_LOG_FATAL of
Do we need it? If yes, we can expose it here

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/p_seccomp/p_seccomp.c
> -                  p_print_log(P_LKRG_INFO, "Updating ED pid[%d]\n",p_threads->pid);
Oh Now i see you move it inside  to the function `p_update_ed_process`. In fact the main idea why I was keeping it in the callers is because during various debug I could track from where the update come from and where it was missed. I was manually instrumenting the appropriate messages to find out whats going on. I guess in the debug build we can read the caller from the stack to find it out

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/p_seccomp/p_seccomp.c
> -                  p_print_log(P_LKRG_INFO, "Updating ED pid[%d]\n",p_threads->pid);
My previous comments why it was removed should not apply :)

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/p_wake_up_new_task/p_wake_up_new_task.c
> -               p_print_log(P_LKRG_WARN,
why remove it?

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/kmod/p_kmod_notifier.c
> +   p_print_log(P_LOG_WATCH, "Module loading blocked");
Shouldn't it be ALERT?

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/print_log/p_lkrg_print_log.h
> - #define LKRG_DEBUG_TRACE notrace
why?

2022-07-15 19:58 UTC, Adam-pi3 commented on src/p_lkrg_main.c
> +p_sym_error:
This is wrong. This should be pointing to the place where `p_main_error` is, otherwise we would not do a good cleanup and crash the kernel on some cases.

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +#define P_KINT_IF_ACCEPT(old, new) \
Move to `.h`

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> -            printk(KERN_CRIT "copy[0x%x] vs now[0x%x] offset[%d | 0x%x] symbol[%s]\n",
Same story as in DEBUG OFF flag. If this special compilation is enabled, I think it should be CRIT to not be overwhelmed with other debug messages

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +#define P_PRINT_WATCH_FEWER(lost_or_extra, nr1, name1, nr2, list2, name2) \
Move to `.h`

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +#define P_PRINT_ONGOING(lost_or_extra) \
Move to `.h`

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +#define P_PRINT_LIVE_OR_NOT \
Move to `.h`

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +#define P_PRINT_ALERT_FEWER(nr1, name1, nr2, list2, name2) \
Move to `.h`

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +#define P_PRINT_FOUND_MORE \
Move to `.h`

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +#define P_PRINT_NOT_IN_KOBJ \
Move to `.h`

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +#define P_PRINT_NOT_IN_OS \
Move to `.h`

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +                           P_PRINT_LIVE_OR_NOT
Do we have missing `p_hack_check++` ?

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +                        P_PRINT_LIVE_OR_NOT
Do we have missing `p_hack_check++` ?

2022-07-15 19:58 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +#define P_PRINT_IN_DB_KOBJ \
Move to `.h`

2022-07-16 00:43 UTC, solardiz commented on src/modules/comm_channel/p_comm_channel.c
> +                     p_tmp, p_str[p_tmp],
Readability. Grouping the arguments in this case by "from" vs. "to" is logical, and having fewer lines is beneficial - more fits on screen, the text is quicker to scroll. Could as well put them all on one line, but splitting them one per line is I think the worst.

2022-07-16 00:45 UTC, solardiz commented on src/modules/comm_channel/p_comm_channel.c
> +         p_print_log(P_LOG_STATE, "Changing pint_enforce from %d (%s) to %d (%s)",
We could, but I think the Linux kernel generally doesn't, and we're not consistent in what we use for different symbols in messages. I had actually added this to my notes while working on this PR:

```
standardize on single or double quotes or no quotes or angle or square brackets for embedded symbol names and sysctl names
```

This lists 5 different kinds of quoting of symbols that I saw in LKRG codebase. I think we don't need that many.

2022-07-16 00:47 UTC, solardiz commented on src/modules/database/CPU.c
> +#define P_CMP_CPU(which) \
No, I think we shouldn't have a general rule of `macros should be defined in .h file not in the middle of .c`. Some macros are far more readable when defined in the context that they're used in locally.

2022-07-16 00:49 UTC, solardiz commented on src/modules/database/CPU.c
> +      p_print_log(P_LOG_FAULT, "Number of " #which " CPUs changed unexpectedly (expected %u, actual %u)", \
My logic is to use `ALERT` only when LKRG is able to produce a response. Currently, to this condition it never responds, meaning we don't consider it severe enough or a reliable enough indicator of attack.

As to malware changing something on only one CPU core, that's separate - it probably wouldn't involve changing the number of CPUs in use.

2022-07-16 00:54 UTC, solardiz commented on src/modules/database/FTRACE/p_ftrace_modify_all_code/p_ftrace_modify_all_code.c
>        return P_LKRG_GENERAL_ERROR;
We could unify the `register_kretprobe` somehow, but that shouldn't be part of the unification of symbol lookups because it's not a symbol lookup.

BTW, these vary between `FATAL` and `ISSUE`, so that would need to be an argument to the macro (or whatever we use).

2022-07-16 00:56 UTC, solardiz commented on src/modules/database/arch/p_arch_metadata.c
> +             "It's OK, but tracepoints might be not be supported correctly "
Oh, should remove the extra "be". Will do.

2022-07-16 00:59 UTC, solardiz commented on src/modules/database/arch/p_arch_metadata.c
>        return P_LKRG_GENERAL_ERROR;
We wouldn't achieve much by replacing a `return` with a `goto`. We could, however, wrap these calls/prints/returns into a macro, if they're similar and numerous enough.

2022-07-16 01:05 UTC, solardiz commented on src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
> -            p_print_log(P_LKRG_CRIT, "We might be killing arbitrary process here. However, it is worth the risk!\n");
I considered that, and don't have strong feelings either way, but I'm not happy with the log message and didn't come up with a better one.

One of the issues with that message is we're not actually sure we'll be killing. `p_ed_kill_task_by_task()` has a `switch` of its own, and could choose to `panic()`. Duplicating that logic here is undesirable.

2022-07-16 01:07 UTC, solardiz commented on src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
> +            panic(P_LKRG_SIGNATURE "BLOCK: CPU: SMEP got disabled");
`BLOCK` in panic messages is for detection by the same kind of automated log parsing (if this does get in a log at all, such as with `netconsole` or something) that applies to alerts. However, they're not identical in other ways anyway, and as we've discussed I'm going to introduce a wrapper around `panic()` that would also issue alerts, and then can drop `BLOCK` from panic messages.

2022-07-16 01:08 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> +     "Can't hook 'ovl_create_or_link' function. This is expected when not using OverlayFS.",
OK

2022-07-16 01:09 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_ERR, "kmem_cache_create() for exploit detection validation error! :(\n");
I felt the message produced by the caller is sufficient.

2022-07-16 01:16 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_CRIT, "Before overwrite:\n");
A debugging message is certainly not an alert, even when deliberately debugging. OK, I'll upgrade the messages for `P_LKRG_TASK_OFF_DEBUG` to `WATCH`.

2022-07-16 01:19 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> +static inline void p_ed_is_off_off(struct p_ed_process *p_source, long p_val, int *p_ret) {
Yes, you could prefer to look at the original and final code, not at the diff here. The diff does look weird.

2022-07-16 01:23 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> -int p_print_task_f(void *p_arg) {
`p_print_task_f` is unused. I understand you might have been putting it to use with source code edits while debugging, but I felt you can just as easily patch a print into `p_dump_task_f`.

2022-07-16 01:29 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> -         p_print_log(P_LKRG_INFO,
We do have that info:

`p_iterate_processes` is only called with `p_dump_task_f` as `p_func`, and `p_dump_task_f` only returns non-zero when it has logged a message about what happened. It's one of these two:

```c
      p_print_log(P_LOG_FAULT, "Can't allocate memory for tracking pid %u, name %s", p_task->pid, p_task->comm);
      return P_LKRG_GENERAL_ERROR;
```

or

```c
      p_print_log(P_LOG_WATCH, "pid %u is already inserted", p_tmp->p_ed_task.p_pid);
      p_free_ed_pids(p_tmp);
      return 1;
```

So the logging from the loop in `p_iterate_processes` was redundant, and is now removed.

2022-07-16 01:40 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> +         return -1;
No, it shouldn't be `P_LKRG_GENERAL_ERROR` here. That function returns the number of corruptions, and I introduced negative as indicating it already killed - so the caller doesn't need to duplicate-kill. This is also why I `return` early in this case - otherwise I'd need to introduce some complexity on tracking this status till the end of function. ...OK, I just did, and it's not much complexity.

2022-07-16 01:47 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> +   P_CMP_PTR(p_orig->p_ed_task.p_nsproxy, p_current->nsproxy, "nsproxy")
OK, I'm adding `"Namespace escape: "`

2022-07-16 01:48 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_ERR, "kmem_cache_create() for exploit detection pCFI error! :(\n");
The caller prints a message, and this is the only error possible in this function.

2022-07-16 01:51 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_CRIT,
`p_ed_pcfi_validate_sp` already logs a more specific message, repeating that in the caller was redundant.

2022-07-16 01:52 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> +   if (unlikely(p_sp & (sizeof(long) - 1))) {
I don't mind removing the stack alignment check, but I treat that as separate from the logging updates.

2022-07-16 01:54 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> +   P_SYM_INIT(selinux_enabled, int *)
Maybe, but not a change I'd make as part of this PR.

2022-07-16 01:55 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.h
> -int p_print_task_f(void *p_arg);
`p_print_task_f` is not used even in debug builds.

2022-07-16 01:57 UTC, solardiz commented on src/modules/exploit_detection/syscalls/p_install.c
> + * does not expose the p_fatal flag in here.  It does a final P_LOG_FATAL of
Not really, it's just `FATAL` vs. `ISSUE` here. We have to use `ISSUE` in all cases here for now. We do produce a `FATAL` in the caller afterwards if this ended up fatal.

2022-07-16 02:00 UTC, solardiz commented on src/modules/exploit_detection/syscalls/p_wake_up_new_task/p_wake_up_new_task.c
> -               p_print_log(P_LKRG_WARN,
`p_dump_task_f` already logs an error (currently that would be a `FAULT` about its memory allocation), also doing it in the caller would be redundant.

2022-07-16 02:04 UTC, solardiz commented on src/modules/kmod/p_kmod_notifier.c
> +   p_print_log(P_LOG_WATCH, "Module loading blocked");
No, I think this is only reached after:

```c
      p_print_log(P_LOG_ALERT, "BLOCK: Module: Loading of module name %s", p_kmod->name);
      p_kmod->init = p_block_always;
```

So it's a duplicate/debugging message there.

2022-07-16 02:06 UTC, solardiz commented on src/modules/print_log/p_lkrg_print_log.h
> - #define LKRG_DEBUG_TRACE notrace
That's part of "Fix build without P_LKRG_DEBUG", which includes making `LKRG_DEBUG_TRACE` defined in some way (sometimes to empty) in all builds - thus, outside of this `#if` block.

2022-07-16 02:08 UTC, solardiz commented on src/p_lkrg_main.c
> +p_sym_error:
I think you misread, notice it does `goto p_main_error;`

```c
p_sym_error:
   p_ret = P_LKRG_GENERAL_ERROR;
   goto p_main_error;
```

2022-07-16 02:12 UTC, solardiz commented on src/modules/integrity_timer/p_integrity_timer.c
> -            printk(KERN_CRIT "copy[0x%x] vs now[0x%x] offset[%d | 0x%x] symbol[%s]\n",
OK, I'll upgrade to `WATCH`.

2022-07-16 02:16 UTC, solardiz commented on src/modules/integrity_timer/p_integrity_timer.c
> +                           P_PRINT_LIVE_OR_NOT
I think no, all the `p_hack_check++` are in place right next to where we produce `ALERT`.

2022-07-16 02:16 UTC, solardiz commented on src/modules/integrity_timer/p_integrity_timer.c
> +                        P_PRINT_LIVE_OR_NOT
I think no, all the `p_hack_check++` are in place right next to where we produce `ALERT`.

2022-07-16 02:28 UTC, solardiz commented
@Adam-pi3 Thank you for your review! I've pushed the changes that should address your criticism, please click on "force-pushed" to see what changed.

2022-07-16 15:10 UTC, Adam-pi3 commented on src/modules/comm_channel/p_comm_channel.c
> +         p_print_log(P_LOG_STATE, "Changing pint_enforce from %d (%s) to %d (%s)",
I agree we should standardize it. I think we should keep consistent with the macro which you created:
```
      p_print_log(P_LOG_FATAL, "Can't find '" #sym "'"); \
```
and use ' char.

2022-07-16 15:13 UTC, Adam-pi3 commented on src/modules/database/FTRACE/p_ftrace_modify_all_code/p_ftrace_modify_all_code.c
>        return P_LKRG_GENERAL_ERROR;
OK

2022-07-16 15:14 UTC, Adam-pi3 commented on src/modules/database/arch/p_arch_metadata.c
>        return P_LKRG_GENERAL_ERROR;
Usually they are and this is what @oshogbo did when he refactor exploit detection initialization routine. As you mentioned above, we should do such cleanup probably in a separate PR

2022-07-16 15:16 UTC, Adam-pi3 commented on src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
> -            p_print_log(P_LKRG_CRIT, "We might be killing arbitrary process here. However, it is worth the risk!\n");
We can do filtering to not kill PID==1 here. Regardless, I think we should have such message indicating what's going on and also indirectly telling us which code was responsible for such action

2022-07-16 15:17 UTC, Adam-pi3 commented on src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
> +            panic(P_LKRG_SIGNATURE "BLOCK: CPU: SMEP got disabled");
Thanks

2022-07-16 15:19 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_ERR, "kmem_cache_create() for exploit detection validation error! :(\n");
Hm right... but in such case I would modify this message:
```
   if (p_ed_wq_valid_cache_init()) {
      p_print_log(P_LOG_FATAL, "Can't initialize WQ cache");
      p_ret = P_LKRG_GENERAL_ERROR;
      goto p_exploit_detection_init_out;
   }
```
to indicate which exactly WQ initialization failed since we have a few of them. In such case the same would apply to other kmem caches.

2022-07-16 15:20 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_CRIT, "Before overwrite:\n");
Thx

2022-07-16 15:20 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +static inline void p_ed_is_off_off(struct p_ed_process *p_source, long p_val, int *p_ret) {
Will do

2022-07-16 15:22 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> -int p_print_task_f(void *p_arg) {
In theory yes, but I know it is useful when you do deep debugging and likely I will write it again... can we wrap it in
```
#If 0
...
#endif`
block or something similar?

2022-07-16 15:26 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> -         p_print_log(P_LKRG_INFO,
I see. thx

2022-07-16 15:27 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +         return -1;
OK

2022-07-16 15:28 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +   P_CMP_PTR(p_orig->p_ed_task.p_nsproxy, p_current->nsproxy, "nsproxy")
Thx, it should also apply to the sub-level of escape to tell which specific namespace was escaped

2022-07-16 15:29 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_ERR, "kmem_cache_create() for exploit detection pCFI error! :(\n");
I see, thx

2022-07-16 15:29 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_CRIT,
OK

2022-07-16 15:30 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +   if (unlikely(p_sp & (sizeof(long) - 1))) {
OK, let's keep it as cleanup PR

2022-07-16 15:30 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +   P_SYM_INIT(selinux_enabled, int *)
OK, we should keep track of what we want to include in clean-up PR and extra features like that

2022-07-16 15:36 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_rb_ed_trees/p_rb_ed_pids/p_rb_ed_pids_tree.c
> -      p_print_log(P_LKRG_ERR, "kmem_cache_create() for ED PIDs error! :(\n");
I see we already have that info

2022-07-16 15:37 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/p_install.c
> + * does not expose the p_fatal flag in here.  It does a final P_LOG_FATAL of
OK, maybe we should remove this comment?

2022-07-16 15:39 UTC, Adam-pi3 commented on src/modules/kmod/p_kmod_notifier.c
> +   p_print_log(P_LOG_WATCH, "Module loading blocked");
right. However, this message "Module loading blocked" is generated by blocked module itself, while "BLOCK: Module: Loading..." is generated by LKRG. There will be some time diff. Anyway, I think you are right and WATCH can be sufficient.

2022-07-16 15:39 UTC, Adam-pi3 commented on src/p_lkrg_main.c
> +p_sym_error:
Oh I see... yes :)

2022-07-16 15:49 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +                           P_PRINT_LIVE_OR_NOT
I think this (and next one) are special case. We detected different # of modules in DB and in OS via module list (less in DB). Although, in this case, `p_module_activity` is taken but the extra module form the ongoing KMOD activity is not the same as the one which is 'extra / lost'. This should be `p_hack_check++`

2022-07-16 15:50 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +                        P_PRINT_LIVE_OR_NOT
... and this one as well. We detected different # of modules in DB and in OS via module list (less in DB). Although, in this case, `p_module_activity` is NOT taken at all so we should not have such situation in normal cases. This should be `p_hack_check++`

2022-07-16 16:10 UTC, solardiz commented on src/modules/comm_channel/p_comm_channel.c
> +         p_print_log(P_LOG_STATE, "Changing pint_enforce from %d (%s) to %d (%s)",
That `"Can't find '" #sym "'"` is simply consistent with what those messages used before being moved into the macro, and also consistent with:

```c
      p_print_log(P_LOG_FATAL, "Can't find 'kallsyms_lookup_name'");
```

I'm not sure single quotes are actually most appropriate, and to standardize all of the LKRG messages to use the same kind of quoting for all kinds of symbols would involve more changes than currently are in this PR. But we may.

2022-07-16 16:12 UTC, solardiz commented on src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
> +            panic(P_LKRG_SIGNATURE "BLOCK: CPU: Write Protection got disabled");
I think I'll add `p_panic()` to this PR.

2022-07-16 16:15 UTC, solardiz commented on src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
> -            p_print_log(P_LKRG_CRIT, "We might be killing arbitrary process here. However, it is worth the risk!\n");
No, we can't easily/consistently have the pid 1 check in this place - the called function may choose to panic the kernel (if configured so), in which case the pid is irrelevant. We do already have a "message indicating what's going on and also indirectly telling us which code was responsible" - a previous `DETECT` message mentioning what exactly was found wrong with the stack.

2022-07-16 16:21 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_ERR, "kmem_cache_create() for exploit detection validation error! :(\n");
We do have several caches, but only one with WQ in name. I think our current handling of them (after my changes here) is consistent.

```c
   if (p_ed_pcfi_cache_init()) {
      p_print_log(P_LOG_FATAL, "Can't initialize pCFI cache");
      p_ret = P_LKRG_GENERAL_ERROR;
      goto p_exploit_detection_init_out;
   }

   if (p_ed_wq_valid_cache_init()) {
      p_print_log(P_LOG_FATAL, "Can't initialize WQ cache");
      p_ret = P_LKRG_GENERAL_ERROR;
      goto p_exploit_detection_init_out;
   }
```

```c
   if (p_init_rb_ed_pids()) {
      p_print_log(P_LOG_FATAL, "Can't initialize PIDs cache and RB tree");
      p_ret = P_LKRG_GENERAL_ERROR;
      goto p_exploit_detection_init_out;
   }
```

```c
   if (p_offload_cache_init()) {
      p_print_log(P_LOG_FATAL, "Can't initialize offloading cache");
      p_ret = P_LKRG_GENERAL_ERROR;
      goto p_main_error;
   }
```

2022-07-16 16:23 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> -int p_print_task_f(void *p_arg) {
I can introduce `p_print_task_f` for now if you insist (let me know if you do), but I think such debugging left-overs are due to be removed in a further cleanup anyway. There are more of them to remove.

2022-07-16 16:26 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> +   P_CMP_PTR(p_orig->p_ed_task.p_nsproxy, p_current->nsproxy, "nsproxy")
Do you mean instead of e.g. "Namespace escape: pid_ns pointer corruption" use "PID namespace escape: pid_ns pointer corruption"? I'd rather not. While it may look OK in this specific example I gave, I think it's weirder if done for all of these pointer comparisons.

2022-07-16 16:29 UTC, solardiz commented on src/modules/exploit_detection/syscalls/pCFI/p_mark_inode_dirty/p_mark_inode_dirty.c
> -#if 0
As you can see, I'd rather not keep disabled and unmaintained pieces of code in our tree.

2022-07-16 16:30 UTC, solardiz commented on src/modules/exploit_detection/syscalls/p_install.c
> + * does not expose the p_fatal flag in here.  It does a final P_LOG_FATAL of
I'll probably update it to explain why `ISSUE` and not `FATAL`, without that being a `FIXME`.

2022-07-16 16:34 UTC, solardiz commented on src/modules/integrity_timer/p_integrity_timer.c
> +                           P_PRINT_LIVE_OR_NOT
I don't know if you're looking at diffs (displayed in a weird way here) or at final code. Please take a look at the final code.

Anyway, if you insist we should add `p_hack_check++` here and in the other place you mention (I'm not sure which places these are, since you're commenting on the diffs and they're messy!), then you effectively say you had it wrong before the changes in this PR. Is this what you mean?

Also, like I mentioned before, doing a `p_hack_check++` should be tied to us issuing an alert. So surely you're asking for more than just the addition of this increment then, but also for a change of message severity?

For now, I'll assume you're just confused by the diffs.

2022-07-16 22:26 UTC, Adam-pi3 commented on src/modules/comm_channel/p_comm_channel.c
> +         p_print_log(P_LOG_STATE, "Changing pint_enforce from %d (%s) to %d (%s)",
I think we should just add single quote here in sysctl interface when reference to the option name itself (since we do not have anywhere else without any quoting as far as i remember). We can revisit quoting unification in general in LKRG in further cleanup PRs

2022-07-16 22:27 UTC, Adam-pi3 commented on src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
> +            panic(P_LKRG_SIGNATURE "BLOCK: CPU: Write Protection got disabled");
thanks

2022-07-16 22:27 UTC, Adam-pi3 commented on src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
> -            p_print_log(P_LKRG_CRIT, "We might be killing arbitrary process here. However, it is worth the risk!\n");
OK, let's keep it as is

2022-07-16 22:35 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_ERR, "kmem_cache_create() for exploit detection validation error! :(\n");
Right they are unique but I think if we are working on names we should change that:
1. p_offload_cache_init - this is WQ related to offloading system integrity routine
2. p_ed_wq_valid_cache_init - this is WQ related to system integrity as well but related to ED functionality (like SELinux)

What about for the following names:
- for 1. maybe `system integrity` (includes whatever our kINT functionality does) - `"Can't initialize cache for system integrity WQ"`
- for 2. maybe `data integrity` - for now include SELinux only but likely we will add more there. What about `"Can't initialize cache for data integrity WQ"` ?

2022-07-16 22:37 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> -int p_print_task_f(void *p_arg) {
Hm... OK let's remove it now and I will see if I need it very much (if yes, we can reintroduce it)

2022-07-16 22:37 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +   P_CMP_PTR(p_orig->p_ed_task.p_nsproxy, p_current->nsproxy, "nsproxy")
Right, your proposal looks good, "Namespace escape: pid_ns pointer corruption". Same for individual namespaces

2022-07-16 22:38 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/pCFI/p_mark_inode_dirty/p_mark_inode_dirty.c
> -#if 0
OK

2022-07-16 22:38 UTC, Adam-pi3 commented on src/modules/print_log/p_lkrg_print_log.h
> - #define LKRG_DEBUG_TRACE notrace
OK

2022-07-16 22:47 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +                           P_PRINT_LIVE_OR_NOT
> then you effectively say you had it wrong before the changes in this PR. Is this what you mean?

Yes. I'm a bit confused why it was not in the original case. I mean I likely don't remember, but when I look now at the code, if we can't find the module via official KMOD API and we see it in the OS module list then I think I would assume system is at least in a very weird state. I wonder if it is even realistic scenario. In fact, we have 2 options:
1. Do the standard ALERT macro as you do and call `p_hack_check++`
2. Increase the log-level to be as high as possible and do not invoke `p_hack_check++` and see if we ever encounter such situation.

Certainly I would want to have that scenario to be as much visible and unique as possible that we can easily identified that we are exactly in that condition.

2022-07-16 22:47 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +                        P_PRINT_LIVE_OR_NOT
Same here

2022-07-17 14:08 UTC, solardiz commented on src/modules/integrity_timer/p_integrity_timer.c
> +                           P_PRINT_LIVE_OR_NOT
Do you refer only to the "not live" case? Because in the "live" case the message says this condition is OK, so if we make changes to the handling of this case we also need to adjust the message text (to say what?)

Anyway, I'd rather leave this out of this PR. For obvious bug fixes, I am making them in the first few commits here, but this one is non-obvious.

2022-07-17 14:13 UTC, solardiz commented on src/modules/comm_channel/p_comm_channel.c
> +         p_print_log(P_LOG_STATE, "Changing pint_enforce from %d (%s) to %d (%s)",
OK, although before the changes in this PR we used double-quotes for the sysctl names.

2022-07-17 14:25 UTC, solardiz commented
BTW, a minor issue is that changing `log_level` to 0 does not produce any log message now, because we log _after_ the change. The way the code is written now, this isn't trivial to fix.

A workaround could be to use `ALERT` severity for that message, but that would be wrong (it's a configuration change, not indication of an attack, and there's no response action). Another workaround would be to upgrade severity of all `STATE` messages to be same as `ALERT` (but without the `ALERT` keyword)... meaning there would be no way to disable them.

2022-07-17 14:54 UTC, solardiz commented
Implemented that "not trivial" fix now, seems to work:

```diff
+++ b/src/modules/comm_channel/p_comm_channel.c
@@ -37,6 +37,7 @@ static int p_interval_max = 1800;
 
 static int p_log_level_min = P_LOG_MIN;
 static int p_log_level_max = P_LOG_MAX;
+static int p_log_level_new;
 
 static int p_block_module_min = 0;
 static int p_block_module_max = 1;
@@ -203,7 +204,7 @@ struct ctl_table p_lkrg_sysctl_table[] = {
    },
    {
       .procname       = "log_level",
-      .data           = &P_CTRL(p_log_level),
+      .data           = &p_log_level_new,
       .maxlen         = sizeof(unsigned int),
       .mode           = 0600,
       .proc_handler   = p_sysctl_log_level,
@@ -515,12 +516,17 @@ static int p_sysctl_log_level(struct ctl_table *p_table, int p_write,
 #endif
    };
 
-   p_lkrg_open_rw();
    if ( (p_ret = proc_dointvec_minmax(p_table, p_write, p_buffer, p_len, p_pos)) == 0 && p_write) {
+      int increasing = p_log_level_new > P_CTRL(p_log_level);
+      p_lkrg_open_rw();
+      if (increasing)
+         P_CTRL(p_log_level) = p_log_level_new;
       p_print_log(P_LOG_STATE, "Changing 'log_level' to %d (%s)",
-                  P_CTRL(p_log_level), p_log_level_string[P_CTRL(p_log_level)]);
+                  p_log_level_new, p_log_level_string[p_log_level_new]);
+      if (!increasing)
+         P_CTRL(p_log_level) = p_log_level_new;
+      p_lkrg_close_rw();
    }
-   p_lkrg_close_rw();
 
    return p_ret;
 }
```

2022-07-17 15:03 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> -      p_print_log(P_LKRG_ERR, "kmem_cache_create() for exploit detection validation error! :(\n");
OK, let's use "Can't initialize cache for system integrity WQ" and "Can't initialize cache for data integrity WQ".

2022-07-17 15:06 UTC, solardiz commented on src/modules/exploit_detection/syscalls/p_install.c
> + * does not expose the p_fatal flag in here.  It does a final P_LOG_FATAL of
Changing the comment to:

```c
/*
 * We use ISSUE rather than perhaps FATAL here because p_exploit_detection.c
 * does not expose the p_fatal flag in here and some of these are non-fatal.
 */
```

2022-07-17 16:00 UTC, solardiz commented on src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
> -            p_print_log(P_LKRG_CRIT, "We might be killing arbitrary process here. However, it is worth the risk!\n");
Actually, I proceeded to revise the killing of current task on WP/SMEP/SMAP. I think ideally it'd be a separate enforcement mode for those settings, but for now I implemented what I felt was best given the enforcement modes we have. I'll push soon, please take a look.

2022-07-17 16:14 UTC, solardiz commented on src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
> +            panic(P_LKRG_SIGNATURE "BLOCK: CPU: Write Protection got disabled");
`p_panic()` added

2022-07-17 19:40 UTC, Adam-pi3 commented on src/modules/integrity_timer/p_integrity_timer.c
> +                           P_PRINT_LIVE_OR_NOT
OK, let's revisit it later

2022-07-17 20:04 UTC, Adam-pi3 requested changes

2022-07-17 20:04 UTC, Adam-pi3 commented on src/modules/comm_channel/p_comm_channel.c
> +      if (!increasing)
Do we need to 2 if() blocks? Isn't simpler to always update `P_CTRL(p_log_level)` after we `print(P_LOG_STATE` ?

2022-07-17 20:06 UTC, Adam-pi3 commented
> These are two WATCH level messages. Maybe for consistency I should for now revert them to 0x%lx and drop the FIXME.
> What do you think? For this PR, and longer term. (Two separate questions and answers.)

I think we should replace `%p` with `0x%lx` everywhere

2022-07-17 20:12 UTC, solardiz commented on src/modules/comm_channel/p_comm_channel.c
> +      if (!increasing)
We do need the two `if` because we want to ensure that a message is logged when changing from 0 or changing to 0.

2022-07-17 20:13 UTC, solardiz commented
> I think we should replace `%p` with `0x%lx` everywhere

This is already done in the latest revision here.

2022-07-17 20:16 UTC, Adam-pi3 commented on src/modules/comm_channel/p_comm_channel.c
> +      if (!increasing)
Right hm... OK

2022-07-17 20:17 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +      p_debug_log(P_LOG_DEBUG, "'off' flag[0x%lx] (normalization via 0x%lx)",
I think that's the last change which i think we should have before merging this PR :) Sorry for being picky.

2022-07-17 20:19 UTC, Adam-pi3 commented on src/modules/comm_channel/p_comm_channel.c
> +      if (!increasing)
In fact we can simplify it but this is also OK

2022-07-17 20:22 UTC, solardiz commented
I think longer-term (after this PR), we need to revisit `%p`, though.

2022-07-17 20:23 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
> +      p_debug_log(P_LOG_DEBUG, "'off' flag[0x%lx] (normalization via 0x%lx)",
Change made (being careful to use `p_debug_log` with `P_LOG_DEBUG`).

2022-07-17 20:25 UTC, solardiz commented on src/modules/comm_channel/p_comm_channel.c
> +      if (!increasing)
We could alternatively make changes inside `p_print_log`, sure as introduce an OR'able flag that would bypass the severity check. However, that might not be simpler, and it would complicate the optimizer's job for all uses of that macro.

2022-07-17 20:37 UTC, Adam-pi3 approved these changes

2022-07-17 20:39 UTC, merged

2022-07-20 16:17 UTC, solardiz commented
I proceeded with further testing of these changes by artificially triggering violations. Using this hack:

```diff
+++ b/src/modules/hashing/p_lkrg_fast_hash.c
@@ -31,6 +31,8 @@ notrace uint64_t p_lkrg_fast_hash(const char *p_data, unsigned int p_len) {
    uint64_t p_tmp = 0;
 
    p_lkrg_siphash(p_data, p_len, (uint8_t *)&p_global_siphash_key, (uint8_t *)&p_tmp, sizeof(p_tmp));
+static unsigned int cnt = 0;
+if (cnt++ % 1000 == 500) p_tmp++;
    return p_tmp;
 }
 
```

I am getting one kernel integrity violation (of different kinds) approximately per 5 to 10 invocations of `sysctl lkrg.trigger=1`. Here's what they look like at default log level, with `kint_enforce` reduced to 1 not to trigger a kernel panic:

```
[109028.113726] LKRG: ALERT: DETECT: CPU: Hash of CPU metadata has changed unexpectedly
[109028.129089] LKRG: ALERT: DETECT: Kernel: 1 checksums changed unexpectedly
[109053.543237] LKRG: ALERT: DETECT: Kernel: Module hash changed unexpectedly, name ip6table_filter
[109053.543280] LKRG: ALERT: DETECT: Kernel: Module list hash changed unexpectedly
[109053.543309] LKRG: ALERT: DETECT: Kernel: 2 checksums changed unexpectedly
[109090.344583] LKRG: ALERT: DETECT: Kernel: Module hash changed unexpectedly, name iptable_nat
[109090.344627] LKRG: ALERT: DETECT: Kernel: Module list hash changed unexpectedly
[109090.344648] LKRG: ALERT: DETECT: Kernel: 2 checksums changed unexpectedly
```

As I mentioned before, the actual hash differences are hidden unless the log level is increased to include `WATCH`.

That it says "2 checksums changed unexpectedly" is kind of wrong - it separately counts the changed module hash and the changed module list hash, but as I understand the latter is implied when any module hash is different. Should we fix this, and how?

With `log_level=4`:

```
[109183.671541] LKRG: STATE: Changing 'log_level' to 4 (WATCH)
[109183.672311] LKRG: WATCH: Removing pid 23058
[109185.607513] LKRG: WATCH: Updating pid 23061
[109185.607535] LKRG: WATCH: Inserting pid 23061
[109185.608897] LKRG: WATCH: Updating pid 23061
[109185.629921] LKRG: WATCH: Removing pid 23061
[109192.161615] LKRG: WATCH: Hash of CPU metadata expected 0x394c7d27d70107b9 vs. actual 0x394c7d27d70107b9
[109192.161677] LKRG: WATCH: Exception table hash expected 0x799aba4b5bdcf1c4 vs. actual 0x799aba4b5bdcf1c4
[109192.173882] LKRG: WATCH: _stext hash expected 0x6b583636fcea711d vs. actual 0x6b583636fcea711d
[109192.177027] LKRG: WATCH: _rodata hash expected 0xf3b590df62672caa vs. actual 0xf3b590df62672caa
[109192.177046] LKRG: WATCH: IOMMU table hash expected 0xffffffff vs. actual 0xffffffff
[109192.177059] LKRG: WATCH: Hash from 'module list' => [0x862a372b98ef6cf]
[109192.177069] LKRG: ALERT: DETECT: Kernel: Module hash changed unexpectedly, name nf_nat
[109192.177079] LKRG: WATCH: Module hash expected 0x4f5d3aec3653ae66 vs. actual 0x4f5d3aec3653ae67, name nf_nat
[109192.177092] LKRG: ALERT: DETECT: Kernel: Module list hash changed unexpectedly
[109192.177102] LKRG: WATCH: Module list hash expected 0x974375ea08b44cd9 vs. actual 0x862a372b98ef6cf
[109192.177118] LKRG: WATCH: Hash from 'module kobj(s)' => [0x1215cb315068e0a6]
[109192.177127] LKRG: ALERT: DETECT: Kernel: 2 checksums changed unexpectedly
[109194.619156] LKRG: WATCH: Updating pid 23070
[109194.619218] LKRG: WATCH: Inserting pid 23070
[109194.623231] LKRG: WATCH: Updating pid 23070
[109194.631440] LKRG: WATCH: Removing pid 23070
```

Notice how this lists some hash values even when there's no difference. However, it also additionally logs the differences.

Also, notice how the individual module's hash changed by 1 (our hack), whereas the module list hash changed completely. This confirms my understanding that the latter is a result of the former.

Also, this is pretty verbose. I wonder if we should possibly downgrade most of these messages to DEBUG, continuing to use WATCH for the actually different hashes. However, that would take another pass over the entire LKRG source code to keep things consistent.

2022-07-20 16:25 UTC, solardiz commented
```diff
+++ b/src/modules/exploit_detection/p_exploit_detection.c
@@ -1886,6 +1886,9 @@ int p_ed_pcfi_validate_sp(struct task_struct *p_task, struct p_ed_process *p_ori
       return P_LKRG_SUCCESS;
    }
 
+static unsigned int cnt = 0;
+if (cnt++ % 100000 == 5000) p_sp++;
+
 #define P_PRINT_LOG_STACK(what) \
    if (P_CTRL(p_log_level) >= P_LOG_WATCH) \
       p_print_log(P_LOG_ALERT, "DETECT: Task: Stack " what " (base 0x%lx, sp 0x%lx) for pid %u, name %s", \
```

Correctly triggers this:

```
[109951.907287] LKRG: ALERT: DETECT: Task: Stack pointer misaligned for pid 24758, name dmesg
[109951.907313] LKRG: ALERT: BLOCK: Task: Killing pid 24758, name dmesg
```

2022-07-20 16:43 UTC, solardiz commented
```diff
+++ b/src/modules/exploit_detection/p_exploit_detection.c
@@ -1654,6 +1654,9 @@ int p_ed_enforce_pcfi(struct task_struct *p_task, struct p_ed_process *p_orig, s
    else
       p_sp_addr = p_regs_get_sp(p_regs);
 
+static unsigned int cnt = 0;
+if (cnt++ % 10000 == 5000) p_sp_addr+=800;
+
    if (p_ed_pcfi_validate_sp(p_task,p_orig,p_sp_addr)) {
       // kill this process!
       p_pcfi_kill_task_by_task(p_task);
```

gave me this:

```
[2688491.294841] LKRG: ALERT: DETECT: Task: Stack base invalid for pid 454628, name gcc
[2688491.297895] LKRG: ALERT: DETECT: Task: Stack size mismatch for pid 454628, name gcc
[2688491.298242] LKRG: ALERT: BLOCK: Task: Killing pid 454628, name gcc
[2688491.792674] LKRG: ALERT: DETECT: Task: Stack base invalid for pid 454732, name sh
[2688491.793280] LKRG: ALERT: DETECT: Task: Stack size mismatch for pid 454732, name sh
[2688491.793596] LKRG: ALERT: BLOCK: Task: Killing pid 454732, name sh
[2688492.264462] LKRG: ALERT: DETECT: Task: Stack base invalid for pid 454866, name sh
[2688492.264902] LKRG: ALERT: DETECT: Task: Stack size mismatch for pid 454866, name sh
[2688492.265277] LKRG: ALERT: BLOCK: Task: Killing pid 454866, name sh
[2688499.323131] LKRG: ALERT: DETECT: Task: Stack base invalid for pid 455129, name sh
[2688499.327390] LKRG: ALERT: DETECT: Task: Stack size mismatch for pid 455129, name sh
[2688499.327797] LKRG: ALERT: BLOCK: Task: Killing pid 455129, name sh
```

However, adding 8 in place of 800 went undetected, perhaps because we always hit:

```
[2688459.991783] LKRG: DEBUG: Frame pointer is not on the stack, so CFI is not enforced
```

This is on AlmaLinux 8.5, kernel 4.18.0-348.23.1.el8_5.x86_64. I had seen the same on another system before. Since this is a debug message that is normally suppressed, we don't really know how common this this - but I guess very common. So we skip the heavier pCFI check on many (most?) systems.

2022-07-20 16:53 UTC, solardiz commented
```diff
@@ -1232,6 +1232,8 @@ int p_cmp_creds(struct p_cred *p_orig, const struct cred *p_current_cred, struct
    P_CMP_CRED(gid_eq, p_get_gid, fsgid)
 
 #define P_CMP_PTR(orig, curr, name) \
+{static unsigned int cnt = 0; \
+if (cnt++ % 10000 == 5000) orig = (void *)((char *)orig + 1);} \
    if (orig != curr) { \
       if (p_opt) { \
          if (P_CTRL(p_log_level) >= P_LOG_WATCH) \
```

gave me:

```
[111624.429555] LKRG: ALERT: DETECT: Task: Namespace escape: user_ns pointer corruption for pid 703, name dmesg
[111624.429585] LKRG: ALERT: DETECT: Task: Namespace escape: nsproxy pointer corruption for pid 703, name dmesg
[111624.429603] LKRG: ALERT: DETECT: Task: Namespace escape: uts_ns pointer corruption for pid 703, name dmesg
[111624.429618] LKRG: ALERT: DETECT: Task: Namespace escape: ipc_ns pointer corruption for pid 703, name dmesg
[111624.429633] LKRG: ALERT: DETECT: Task: Namespace escape: mnt_ns pointer corruption for pid 703, name dmesg
[111624.429648] LKRG: ALERT: DETECT: Task: Namespace escape: pid_ns_for_children pointer corruption for pid 703, name dmesg
[111624.429668] LKRG: ALERT: DETECT: Task: Namespace escape: net_ns pointer corruption for pid 703, name dmesg
[111624.429684] LKRG: ALERT: DETECT: Task: Namespace escape: cgroup_ns pointer corruption for pid 703, name dmesg
[111624.429703] LKRG: ALERT: ALLOW: Task: Accepting unexpected changes for pid 703, name dmesg
[111662.728979] LKRG: STATE: Changing 'pint_enforce' from 0 (LOG & ACCEPT) to 1 (KILL TASK)
[111697.723484] LKRG: ALERT: DETECT: Task: Namespace escape: user_ns pointer corruption for pid 775, name vim
[111697.723503] LKRG: ALERT: BLOCK: Task: Killing pid 775, name vim
[111697.723514] LKRG: ALERT: DETECT: Task: Namespace escape: user_ns pointer corruption for pid 775, name vim
[111697.723526] LKRG: ALERT: DETECT: Task: Namespace escape: nsproxy pointer corruption for pid 775, name vim
[111697.723537] LKRG: ALERT: DETECT: Task: Namespace escape: uts_ns pointer corruption for pid 775, name vim
[111697.723548] LKRG: ALERT: DETECT: Task: Namespace escape: ipc_ns pointer corruption for pid 775, name vim
[111697.723559] LKRG: ALERT: DETECT: Task: Namespace escape: mnt_ns pointer corruption for pid 775, name vim
[111697.723570] LKRG: ALERT: DETECT: Task: Namespace escape: pid_ns_for_children pointer corruption for pid 775, name vim
[111697.723582] LKRG: ALERT: DETECT: Task: Namespace escape: net_ns pointer corruption for pid 775, name vim
[111697.723593] LKRG: ALERT: DETECT: Task: Namespace escape: cgroup_ns pointer corruption for pid 775, name vim
[111697.723604] LKRG: ALERT: BLOCK: Task: Killing pid 775, name vim
[111697.723615] LKRG: ALERT: DETECT: Task: Namespace escape: user_ns pointer corruption for pid 775, name vim
[111697.723626] LKRG: ALERT: DETECT: Task: Namespace escape: nsproxy pointer corruption for pid 775, name vim
[111697.723637] LKRG: ALERT: DETECT: Task: Namespace escape: uts_ns pointer corruption for pid 775, name vim
[111697.723648] LKRG: ALERT: DETECT: Task: Namespace escape: ipc_ns pointer corruption for pid 775, name vim
[111697.723659] LKRG: ALERT: DETECT: Task: Namespace escape: mnt_ns pointer corruption for pid 775, name vim
[111697.723669] LKRG: ALERT: DETECT: Task: Namespace escape: pid_ns_for_children pointer corruption for pid 775, name vim
[111697.723682] LKRG: ALERT: DETECT: Task: Namespace escape: net_ns pointer corruption for pid 775, name vim
[111697.723692] LKRG: ALERT: DETECT: Task: Namespace escape: cgroup_ns pointer corruption for pid 775, name vim
[111697.723704] LKRG: ALERT: BLOCK: Task: Killing pid 775, name vim
```

2022-07-20 16:55 UTC, solardiz commented
We have inconsistent logging of sysctl value changes:

```
$ fgrep Changing src/modules/comm_channel/p_comm_channel.c
         p_print_log(P_LOG_STATE, "Changing 'kint_validate' from %d (%s) to %d (%s)",
         p_print_log(P_LOG_STATE, "Changing 'kint_enforce' from %d (%s) to %d (%s)",
         p_print_log(P_LOG_STATE, "Changing 'pint_validate' from %d (%s) to %d (%s)",
         p_print_log(P_LOG_STATE, "Changing 'pint_enforce' from %d (%s) to %d (%s)",
      p_print_log(P_LOG_STATE, "Changing 'interval' to %d", P_CTRL(p_interval));
      p_print_log(P_LOG_STATE, "Changing 'log_level' to %d (%s)",
            p_print_log(P_LOG_STATE, "Changing 'smep_enforce' from %d (%s) to %d (%s)",
            p_print_log(P_LOG_STATE, "Changing 'smap_enforce' from %d (%s) to %d (%s)",
         p_print_log(P_LOG_STATE, "Changing 'umh_validate' from %d (%s) to %d (%s)",
         p_print_log(P_LOG_STATE, "Changing 'umh_enforce' from %d (%s) to %d (%s)",
         p_print_log(P_LOG_STATE, "Changing 'pcfi_validate' from %d (%s) to %d (%s)",
         p_print_log(P_LOG_STATE, "Changing 'pcfi_enforce' from %d (%s) to %d (%s)",
            p_print_log(P_LOG_STATE, "Changing 'profile_validate' from %d (%s) to %d (%s)",
            p_print_log(P_LOG_STATE, "Changing 'profile_enforce' from %d (%s) to %d (%s)",
```

For all of these but `log_level` and `interval`, we include both the old and the new value. Also, for those where we log "Enabling" or "Disabling" instead of numeric values, we only do that when the value has changed. So it's illogical that for `log_level` and `interval` we log a "Changing" message that does not let us see whether the value has changed.

2022-07-20 17:00 UTC, solardiz commented
```diff
@@ -1209,7 +1209,8 @@ int p_cmp_creds(struct p_cred *p_orig, const struct cred *p_current_cred, struct
    int p_ret = 0;
 
 #define P_CMP_CRED(eq, get, cred) \
-   if (!eq(p_orig->cred, p_current_cred->cred)) { \
+{static unsigned int cnt = 0; \
+   if (!eq(p_orig->cred, p_current_cred->cred) || cnt++ % 10000 == 5000) { \
       if (p_opt) { \
          p_print_log(P_LOG_ALERT, \
             "DETECT: Task: " #cred " corruption (expected %u vs. actual %u) for pid %u, name %s", \
@@ -1217,7 +1218,7 @@ int p_cmp_creds(struct p_cred *p_orig, const struct cred *p_current_cred, struct
             task_pid_nr(p_current), p_current->comm); \
       } \
       p_ret++; \
-   }
+   }}
 
    /* *UID */
    P_CMP_CRED(uid_eq, p_get_uid, uid)
```

```
[112218.093848] LKRG: ALERT: DETECT: Task: uid corruption (expected 0 vs. actual 0) for pid 1890, name dmesg
[112218.093874] LKRG: ALERT: DETECT: Task: euid corruption (expected 0 vs. actual 0) for pid 1890, name dmesg
[112218.093892] LKRG: ALERT: DETECT: Task: suid corruption (expected 0 vs. actual 0) for pid 1890, name dmesg
[112218.093909] LKRG: ALERT: DETECT: Task: fsuid corruption (expected 0 vs. actual 0) for pid 1890, name dmesg
[112218.093925] LKRG: ALERT: DETECT: Task: gid corruption (expected 0 vs. actual 0) for pid 1890, name dmesg
[112218.093942] LKRG: ALERT: DETECT: Task: egid corruption (expected 0 vs. actual 0) for pid 1890, name dmesg
[112218.093961] LKRG: ALERT: DETECT: Task: sgid corruption (expected 0 vs. actual 0) for pid 1890, name dmesg
[112218.093978] LKRG: ALERT: DETECT: Task: fsgid corruption (expected 0 vs. actual 0) for pid 1890, name dmesg
[112218.093996] LKRG: ALERT: ALLOW: Task: Accepting unexpected changes for pid 1890, name dmesg
[112244.988450] LKRG: STATE: Changing 'pint_enforce' from 0 (LOG & ACCEPT) to 1 (KILL TASK)
[112252.321586] LKRG: ALERT: DETECT: Task: uid corruption (expected 0 vs. actual 0) for pid 1931, name dmesg
[112252.321610] LKRG: ALERT: DETECT: Task: euid corruption (expected 0 vs. actual 0) for pid 1931, name dmesg
[112252.321630] LKRG: ALERT: DETECT: Task: suid corruption (expected 0 vs. actual 0) for pid 1931, name dmesg
[112252.321647] LKRG: ALERT: DETECT: Task: fsuid corruption (expected 0 vs. actual 0) for pid 1931, name dmesg
[112252.321662] LKRG: ALERT: DETECT: Task: gid corruption (expected 0 vs. actual 0) for pid 1931, name dmesg
[112252.321680] LKRG: ALERT: DETECT: Task: egid corruption (expected 0 vs. actual 0) for pid 1931, name dmesg
[112252.321700] LKRG: ALERT: DETECT: Task: sgid corruption (expected 0 vs. actual 0) for pid 1931, name dmesg
[112252.321717] LKRG: ALERT: DETECT: Task: fsgid corruption (expected 0 vs. actual 0) for pid 1931, name dmesg
[112252.321732] LKRG: ALERT: BLOCK: Task: Killing pid 1931, name dmesg
```

2022-07-20 17:23 UTC, solardiz commented
```diff
+++ b/src/modules/exploit_detection/arch/x86/p_ed_x86_arch.h
@@ -94,6 +94,8 @@ static inline unsigned int p_ed_pcfi_x86_validate_wp(unsigned char p_kill) {
       return p_bad;
 
    p_cr0 = read_cr0();
+static unsigned int cnt;
+if (cnt++ % 1000 == 500) p_cr0=0;
 
    if (!(p_cr0 & X86_CR0_WP)) {
 
```

```
[113350.870302] LKRG: ALIVE: LKRG initialized successfully
[113350.870318] OOM killer enabled.
[113350.870325] Restarting tasks ... done.
[113353.128289] LKRG: ALERT: BLOCK: CPU: Write Protection got disabled, re-enabling
[113358.052838] LKRG: ALERT: BLOCK: CPU: Write Protection got disabled, re-enabling
[113358.079982] LKRG: ALERT: BLOCK: CPU: Write Protection got disabled, re-enabling
[113360.863717] LKRG: ALERT: BLOCK: CPU: Write Protection got disabled, re-enabling
[113362.903155] LKRG: ALERT: BLOCK: CPU: Write Protection got disabled, re-enabling
[113362.919360] LKRG: ALERT: BLOCK: CPU: Write Protection got disabled, re-enabling
[113368.391476] LKRG: STATE: Changing 'pint_enforce' from 0 (LOG & ACCEPT) to 1 (KILL TASK)
[113369.534743] LKRG: ALERT: BLOCK: CPU: Write Protection got disabled, re-enabling
[113369.534770] LKRG: ALERT: BLOCK: Task: About to take chances and kill a task that may be relevant or not
[113369.534787] LKRG: ALERT: BLOCK: Task: Killing pid 975, name gnome-terminal-
```

Within seconds, this killed pretty much everything that tried to move, requiring unclean shutdown.

2022-07-20 17:27 UTC, solardiz commented
> That it says "2 checksums changed unexpectedly" is kind of wrong - it separately counts the changed module hash and the changed module list hash, but as I understand the latter is implied when any module hash is different. Should we fix this, and how?

Just discussed this with @Adam-pi3 - he's for keeping the current behavior. So it stays, at least for now.

2022-07-20 18:01 UTC, solardiz commented
Per suggestion of @Adam-pi3, tested this:

```diff
+++ b/src/modules/exploit_detection/p_exploit_detection.c
@@ -1630,7 +1630,9 @@ int p_ed_enforce_pcfi(struct task_struct *p_task, struct p_ed_process *p_orig, s
    unsigned int i = 0;
 //   unsigned long p_flags;
    struct stack_trace p_trace;
+#ifndef CONFIG_UNWINDER_ORC
    const void *p_fp = (const void *)p_regs_get_fp(p_regs);
+#endif
 #ifdef CONFIG_X86
 #if defined(CONFIG_UNWINDER_ORC)
    struct unwind_state p_state;
@@ -1672,10 +1674,12 @@ int p_ed_enforce_pcfi(struct task_struct *p_task, struct p_ed_process *p_orig, s
       }
    }
 
+#ifndef CONFIG_UNWINDER_ORC
    if (!p_is_obj_on_stack(p_task, p_fp)) {
       p_debug_log(P_LOG_DEBUG, "Frame pointer is not on the stack, so CFI is not enforced");
       goto p_ed_enforce_pcfi_out;
    }
+#endif
 
    while ( (p_trace.entries = p_ed_pcfi_alloc()) == NULL); // Should never be NULL
 
@@ -1836,7 +1840,8 @@ int p_ed_enforce_pcfi(struct task_struct *p_task, struct p_ed_process *p_orig, s
       }
    }
 
-   if (p_not_valid) {
+static unsigned int cnt;
+   if (p_not_valid || cnt++ % 5000 == 500) {
       p_print_log(P_LOG_ALERT, "DETECT: Task: Invalid stack trace for pid %u, name %s",
          task_pid_nr(p_task), p_task->comm);
       if (P_CTRL(p_log_level) >= P_LOG_WATCH) {
```

on AlmaLinux 8.5 with `pcfi_enforce=0`:

```
[ 3024.552393] LKRG: ALERT: DETECT: Task: Invalid stack trace for pid 6378, name bash
[ 3024.552489] LKRG: WATCH: Invalid frame is 7 (0xffffffffbc6000ad) out of 8 for pid 6378, name bash
[ 3024.552489] --- STACK TRACE START ---
[ 3024.552495]  generic_permission+0x1/0x190
[ 3024.552496]  inode_permission+0x29/0x130
[ 3024.552498]  link_path_walk+0x72/0x550
[ 3024.552499]  path_lookupat.isra.49+0x97/0x200
[ 3024.552500]  filename_lookup.part.63+0xa0/0x170
[ 3024.552503]  do_faccessat+0x7c/0x250
[ 3024.552506]  do_syscall_64+0x5b/0x1a0
[ 3024.552509]  entry_SYSCALL_64_after_hwframe+0x65/0xca
[ 3024.552509] --- STACK TRACE END ---
[ 3024.552510] LKRG: ALERT: ALLOW: Task: pCFI validation failed for pid 6378, name bash
```

So apparently we need the first two hunks of the above patch to repair heavy pCFI on systems with ORC.