Add UMH modprobe path for Arch Linux init context
lkrg-org/lkrg pull request #260
Opened 2023-02-02 16:20 UTC by sempervictus

Address #258 by adding /usr/bin/modprobe to the UMH allow-list.

### Description
Fixes booting on Arch Linux when LKRG is built into the kernel binary

### How Has This Been Tested?
Booted in an Arch Linux VM:
```sh
[root@svl-arch00 ~]# uname -r ; modinfo lkrg |head;sysctl -a|grep umh_
6.1.8
name:           lkrg
filename:       (builtin)
license:        GPL v2
file:           security/lkrg/lkrg
description:    pi3's Linux kernel Runtime Guard
author:         Adam 'pi3' Zabrocki (http://pi3.com.pl)
parm:           log_level:log_level [3 (issue) is default] (uint)
parm:           heartbeat:heartbeat [0 (don't print) is default] (uint)
parm:           block_modules:block_modules [0 (don't block) is default] (uint)
parm:           interval:interval [15 seconds is default] (uint)
lkrg.umh_enforce = 1
lkrg.umh_validate = 1
```

2023-02-02 17:00 UTC, Adam-pi3 requested changes

2023-02-02 17:00 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
> +   "/usr/bin/modprobe",
We are trying to keep this list in alphabetic order. Would you be able to move it accordingly?

2023-02-03 00:55 UTC, sempervictus commented on src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
> +   "/usr/bin/modprobe",
All set

2023-02-03 06:48 UTC, Adam-pi3 commented
Thanks @sempervictus !

2023-02-03 06:48 UTC, merged