make bootup scripts independent of cwd, add usage and root checks
lkrg-org/lkrg pull request #278
Opened 2023-07-10 07:36 UTC by vobst

### Description
For my use case it happened that I ran the install scripts not from the root of the project (and not through make). I noticed that they fail "silently" in that case. I thought it would not hurt to update the scripts to be more self-sufficient, i.e., independent of the cwd and with some usage and root checks.

### How Has This Been Tested?
Tested that it works as expected for systemd, cannot say anything about the openrc part.

2023-07-10 18:28 UTC, solardiz requested changes
I made a few comments. These also apply to other instances of the same within the scripts patched here.

2023-07-10 18:28 UTC, solardiz commented on scripts/bootup/lkrg-bootup.sh
> +P_SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
I think the `readlink` part here (and in other scripts you patch similarly) is not necessary. It puts the full absolute path into the variable, but we can also use a relative path (like we did before) since we're not changing directories.

In fact, we use `dirname` alone in `scripts/copy-builtin.sh`, so it's inconsistent to do things differently here.

2023-07-10 18:28 UTC, solardiz commented on scripts/bootup/lkrg-bootup.sh
> +fi
Wrong indentation. We indent with tabs further in the script.

The semicolons within the second `then` ... `fi` are unneeded, probably are typos.

Putting `$#` into double-quotes is weird since it's a numeric shell builtin variable.

I'm not sure we want the `>&2` redirects here, but I don't mind.

2023-07-10 18:28 UTC, solardiz commented on scripts/bootup/openrc/lkrg-openrc.sh
> +set -ue
Let's standardize on `set -eu` (order of arguments) like in the first script patched here.

2023-07-10 18:30 UTC, solardiz commented
Regarding requiring root, I guess we could at some point want to make the opposite move - allow for running the scripts as non-root during package build (installing into a build user writable "buildroot" tree), skipping the actions that require root. However, for now I don't mind introducing the root checks as this is consistent with the current inflexible scripts.

2023-07-10 18:31 UTC, solardiz commented
@mrl5 Please review the OpenRC script changes here. Thank you!

2023-07-10 21:48 UTC, mrl5 reviewed
looks legit! thanks @vobst for fixes and improvements 🚀  
Please consider applying suggestions from comments.

@solardiz if you prefer, I can test it a bit later on an OpenRC system and then leave my approval

2023-07-10 21:48 UTC, mrl5 commented on scripts/bootup/lkrg-bootup.sh
> -		exec "$P_LKRG_OPENRC" "$@"
although it takes only one arg, I'd leave `"$@"` as is

this is just personal preference backed up with a usecase where you introduce another arg and don't need to remember to pass `"$1" "$2"` in bunch of other places

2023-07-11 11:11 UTC, solardiz requested changes
Thanks, the overall changes look good to me now. However, the separation into commits does not. I didn't say it - maybe I should have - but we generally expect that feedback is addressed by making changes to the existing commits and force-pushing, not by adding more commits. What do you use to manage this git branch - do you use git on the command line, or GitHub UI, or something else?

Are you able to easily revise existing commits and force-push? If you are, then please replace the added commit with the corresponding changes included into your first commit instead.

If you are not, then please revert the commit making changes to `README` (add a revert commit) and we'll have to merge this PR via GitHub's squash-and-merge (turning it into just one commit) and get these other changes via your other PR.

2023-07-11 11:17 UTC, solardiz commented
Also, we prefer to mention the changed subsystem or file name in the commit message (near the beginning). Your "make bootup scripts independent of cwd, add usage and root checks" does mention "bootup scripts", but "Add remark about lkrg-bootup.sh to DKMS section" leaves it unclear where the changes are being made (where that "DKMS section" is) without looking at the changes themselves. I suggest replacing the latter commit message with "README: Add remark about lkrg-bootup.sh to DKMS section".

2023-07-11 12:20 UTC, solardiz approved these changes
Looks good to me now. Thank you!

2023-07-11 12:22 UTC, solardiz commented
@mrl5 I think I'll merge this now. You can then test on an OpenRC system and let us know of your results in a comment here, and if there are any issues then send us another PR to fix those (but I don't expect issues). Thank you!

2023-07-11 12:23 UTC, merged